export const ICON_NAMES = {
  MENU: 'menu-outline',
  SEARCH: 'search-outline',
  CALENDAR: 'calendar-outline',
  TODAY: 'today-outline',
  ADD: 'add',
  PERSON: 'person-circle-outline',
  CHECKMARK_CIRCLE: 'checkmark-circle-outline',
  CALENDAR_SOLID: 'calendar',
  CLOSE: 'close',
  TIME: 'time-outline',
  REPEAT: 'sync-outline',
  DESCRIPTION: 'reorder-three-outline',
  CHEVRON_DOWN: 'chevron-down',
  CHECKMARK: 'checkmark',
} as const;
